linters:
  enable:
    - asciicheck
    - errorlint
    - gci
    - gofumpt
    - gosec
    - wastedassign

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/CycloneDX)
    custom-order: true
