builds:
  # This is a library project, we don't want to build any binaries.
  # Building and testing is performed in the CI workflow
  - skip: true
release:
  extra_files:
    - glob: ./bom.json
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
