name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

permissions: { }

jobs:
  licensecheck:
    name: License Check
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # tag=v3.5.3
    - name: Check license headers
      uses: apache/skywalking-eyes@438e4ea5682269933ea2c8b5608662e52af26959 # tag=v0.4.0
      with:
        config: .licenserc.yml

  lint:
    name: Lint
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # tag=v3.5.3
    - name: Setup Go
      uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # tag=v4.0.1
      with:
        go-version: "1.19"
        check-latest: true
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@639cd343e1d3b897ff35927a75193d57cfcba299 # tag=v3.6.0
      with:
        version: latest

  test:
    name: Test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
        - "1.17"
        - "1.18"
        - "1.19"
    steps:
    - name: Setup Go
      uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # tag=v4.0.1
      with:
        go-version: ${{ matrix.go }}
        check-latest: true
    - name: Checkout Repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # tag=v3.5.3
    - name: Test
      run: make test
