name: GoReleaser

on:
  push:
    tags:
    - 'v*'

permissions: { }

jobs:
  goreleaser:
    name: Release
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # tag=v3.4.0
      with:
        fetch-depth: 0
    - name: Setup Go
      uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # tag=v3.5.0
      with:
        go-version: "1.19"
        check-latest: true
    - name: Install cyclonedx-gomod
      uses: CycloneDX/gh-gomod-generate-sbom@d4aee0cf5133055dbd98899978246c10c18c440f # tag=v1.1.0
      with:
        version: v1
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@f82d6c1c344bcacabba2c841718984797f664a6b # tag=v4.2.0
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
